package com.opspilot.incident.infrastructure.persistence;
import com.opspilot.incident.api.*; import com.opspilot.incident.domain.*; import com.opspilot.servicecatalog.application.MonitoredServiceQueryService; import java.time.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class IncidentFacade {
 private final AlertJpaRepository alerts; private final IncidentJpaRepository incidents; private final IncidentAlertJpaRepository links; private final MonitoredServiceQueryService services; private final Clock clock;
 public IncidentFacade(AlertJpaRepository a,IncidentJpaRepository i,IncidentAlertJpaRepository l,MonitoredServiceQueryService s,Clock c){alerts=a;incidents=i;links=l;services=s;clock=c;}
 @Transactional public AlertResponse create(ManualAlertRequest r){ services.get(r.serviceId()); Instant now=Instant.now(clock); AlertEntity a=alerts.save(new AlertEntity(UUID.randomUUID(),UUID.randomUUID(),r.serviceId(),AlertSource.MANUAL,r.alertType(),r.severity(),r.fingerprint().trim(),r.title().trim(),r.message().trim(),r.occurredAt(),now)); IncidentEntity incident=incidents.findFirstByServiceIdAndFingerprintAndStatusNotOrderByCreatedAtDesc(r.serviceId(),a.fingerprint,IncidentStatus.RESOLVED).orElseGet(()->incidents.save(new IncidentEntity(UUID.randomUUID(),r.serviceId(),a.fingerprint,a.severity,a.title,now))); incident.severity=Severity.highest(incident.severity,a.severity); incident.updatedAt=now; incidents.save(incident); links.save(new IncidentAlertEntity(incident.id,a.id)); return alert(a); }
 @Transactional(readOnly=true) public AlertResponse alert(UUID id){return alerts.findById(id).map(this::alert).orElseThrow(()->new NoSuchElementException("Alert "+id+" was not found"));}
 @Transactional(readOnly=true) public PageResponse<AlertResponse> alerts(int page,int size){Page<AlertEntity> p=alerts.findAll(PageRequest.of(page,size,Sort.by("occurredAt").descending()));return new PageResponse<>(p.map(this::alert).getContent(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @Transactional(readOnly=true) public IncidentResponse incident(UUID id){return incidents.findById(id).map(this::incident).orElseThrow(()->new NoSuchElementException("Incident "+id+" was not found"));}
 @Transactional(readOnly=true) public PageResponse<IncidentResponse> incidents(int page,int size){Page<IncidentEntity> p=incidents.findAll(PageRequest.of(page,size,Sort.by("createdAt").descending()));return new PageResponse<>(p.map(this::incident).getContent(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @Transactional public IncidentResponse acknowledge(UUID id){return transition(id,IncidentStatus.ACKNOWLEDGED,null);}
 @Transactional public IncidentResponse investigate(UUID id){return transition(id,IncidentStatus.INVESTIGATING,null);}
 @Transactional public IncidentResponse resolve(UUID id,String summary){return transition(id,IncidentStatus.RESOLVED,summary);}
 private IncidentResponse transition(UUID id,IncidentStatus target,String summary){IncidentEntity i=incidents.findById(id).orElseThrow(()->new NoSuchElementException("Incident "+id+" was not found"));if(i.status==IncidentStatus.RESOLVED)throw new InvalidIncidentStateException("Resolved incidents cannot reopen");if(target==IncidentStatus.ACKNOWLEDGED&&i.status!=IncidentStatus.OPEN)throw new InvalidIncidentStateException("Only open incidents can be acknowledged");if(target==IncidentStatus.INVESTIGATING&&i.status!=IncidentStatus.ACKNOWLEDGED)throw new InvalidIncidentStateException("Only acknowledged incidents can start investigation");if(target==IncidentStatus.RESOLVED&&(summary==null||summary.isBlank()))throw new InvalidIncidentStateException("Resolution summary is required");i.status=target;i.resolutionSummary=summary;i.updatedAt=Instant.now(clock);return incident(incidents.save(i));}
 private AlertResponse alert(AlertEntity a){return new AlertResponse(a.id,a.eventId,a.serviceId,a.source,a.alertType,a.severity,a.fingerprint,a.title,a.message,a.occurredAt,a.createdAt);} private IncidentResponse incident(IncidentEntity i){return new IncidentResponse(i.id,i.serviceId,i.fingerprint,i.status,i.severity,i.title,i.resolutionSummary,i.createdAt,i.updatedAt);} }
